### ISSUE TITLE
dist のファイルが見つからない

### ISSUE THREAD

**Issue by huideyeren** [abcb2/type-gimei#4]
現行バージョンで dist ディレクトリが見つかりませんでした。
そのため、JavaScriptからtype-gimeiを呼ぼうとするとエラーが発生してしまいます。

なお、私がフォークして検証してみたところ、 `npm run build_all` を実行したパッケージでは正常に実行されます。

**Comment by abcb2** [comment]
たて込んでいて今すぐの対応ができないので、しばらくお時間ください:pray:

**Comment by abcb2** [comment]
npmにv1.0.0をpublishしました。そちらを使ってみてください:pray:

**Comment by abcb2** [comment]
すみません。所々の事情でv1.0.2になりました。

https://www.npmjs.com/package/type-gimei/v/1.0.2

**Comment by huideyeren** [comment]
v1.0.2をNPMからインストールしてみましたが、以下のようなメッセージが表示されます。

```
Error: Cannot find module './dist/package/gimei'
```

パッケージにビルド後のJavaScriptが入っていないようです。  
パッケージをpublishする前に `npm run build_all` を実行して、ビルド済みのJavaScriptをパッケージに含める必要があると思います。
